### ISSUE TITLE
Find no documentation to run an own ct-api-server

### ISSUE THREAD

**Issue by dalijolijo** [samotari/ct-api-server#60]
I want to run a ct-api-server for my own environment.
But I can´t find a README for installation and configuration. Please provide me these information.

**Comment by chill117** [comment]
I've added some guidance to the [project readme file](https://github.com/samotari/ct-api-server/blob/master/README.md) that should help you to setup your own instance of the ct-api-server. If you are still stuck, please let me know and I will try to assist further.

**Comment by chill117** [comment]
Closing this because the instructions for running the server are now in the readme.
